# Generated by Django 4.1.1 on 2025-01-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_genre_remove_actor_birth_year_remove_film_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
